version: '3'
services:
  redis:
    image: redis:7.0-alpine
    expose:
      - "6379"

  elastic:
    image: elasticsearch:7.17.0
    expose:
      - "9200"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

  async_api:
    build:
      context: ./src/
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elastic