# Файл должен начинаться с тега версии. Используем последнюю.
version: '3'
services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  elastic:
    image: elasticsearch:7.17.0
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

#  async_api:
#    build:
#      context: ./src/
#    ports:
#      - "8080:8080"
#    depends_on:
#      - redis
##      - elastic
##    expose:
##      - "8000:8080"


# Указываем Docker, какие именованные тома потребуются сервисам
volumes:
  static: