version: '3'
services:
  postgres:
    image: postgres:13
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_DB=${DB_NAME}"

  redis:
    image: redis:7.0-alpine
    expose:
      - "6379"

  etl:
    build:
      context: ./ETL/
    depends_on:
      - elastic
      - postgres
    environment:
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_USER=${DB_USER}"
      - "DB_NAME=${DB_NAME}"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "ES_URL=${ELASTIC_HOST}"
      - "ES_PORT=${ELASTIC_PORT}"

  elastic:
    image: elasticsearch:7.17.1
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

  async_api:
    build:
      context: ./src/
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elastic


